jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: "actions/checkout@v2.1.0"
      - uses: "cachix/install-nix-action@v9"
      - uses: "cachix/cachix-action@v6"
        with:
          name: shopping-cart
          signingKey: "${{ secrets.CACHIX_SIGNING_KEY }}"
      - run: "nix-shell --run \"cabal new-test --test-show-details=streaming\""
name: Haskell CI
on:
  pull_request:
  push:
    branches:
      - master
