name: Haskell CI

on:
  pull_request:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ghc: ["8.8.3"]
        cabal: ["3.2"]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-haskell@v1.1
      id: setup-haskell-cabal
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal }}
    - uses: actions/cache@v1
      name: Cache cabal-store
      with:
        path: ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
        key: ${{ runner.os }}-${{ matrix.ghc }}-cabal
    - name: Install dependencies
      run: |
        cabal new-update
        cabal new-configure --write-ghc-environment-files=always -j2
        cabal new-build --only-dependencies
    - name: Build & Run Tests
      run: |
        cabal new-build
        cabal new-test --test-show-details=streaming
